### ISSUE TITLE
learn -b and learn have different results

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/wordy.js#3]
My disgusting non refactored code passes all tests in the Jasmine, "learn -b" interface.  However, when I run "learn", two tests failures. The two failures are the Argument Error tests at the end of the lab.  https://github.com/garettarrowood/wordy.js-000

**Comment by garettarrowood** [comment]
So I read the next lesson and went back to fix this and got both sets of Learn tests to pass. It's a good idea to either move the "Intro to Custom Errors" before this lab, or rewrite the ArgumentError at the bottom of wordy.js so it is set up correctly.

**Comment by NoneOfMaster** [comment]
This is the second time I'm experiencing this same phenomenon. Looks like I have something to learn in the next lab. Still it seems to me that it should not be possible for there to be a discrepancy in running the same tests in the browser (learn -b) or in on the CLI (learn). Here's the screenshot of 16 tests 0 failures, and 16 test two failures side-by-side, even though they are in fact the same tests run at the same time. I'll push up the code too:

![screen shot 2016-04-10 at 3 40 40 pm](https://cloud.githubusercontent.com/assets/12436033/14413572/1b366de0-ff33-11e5-9872-38533021ea56.png)
